### ISSUE TITLE
Crash in SpringBoard sample when tapping after move

### ISSUE THREAD

**Issue by BenParks** [AlanQuatermain/AQGridView#117]
Hi,

I'm getting a crash in the SpringBoard sample. To reproduce:
1. Start the app
2. Move an item
3. Tap on the item -> EXEC_BAD_ACCESS on 1389 of AQGridView

It seems that when you tap (and hold) the first time it will go through touchesBegan (1315). When you release touchesEnded is not called until the item is released and tapped for the second time.

Any ideas?

Thanks,
Ben

**Comment by BenParks** [comment]
As a temporary work around I made _touchedContentView and strong reference. I suspect this will cause a memory retention issue.

**Comment by LiangQiao** [comment]
I got the same issue!

**Comment by BenParks** [comment]
Final work around was to remove the component completely :( I hope one day to find time to resolve the issue and feedback.

**Comment by jgeller819** [comment]
The problem is that _pendingSelectionIndex wasn't getting set to NSNotFound at the end of the long press. 
Fixed it by adding:

[_photoView touchesEnded:[NSSet set] withEvent:nil]; 

to 
- (void) moveActionGestureRecognizerStateChanged:(UIGestureRecognizer *)recognizer

at the end of the ending case statements (stateEnded, stateCanceled)

**Comment by alekseypotapov-dev** [comment]
@jgeller819  thanks
