### ISSUE TITLE
cannot set usesPagedHorizontalScrolling

### ISSUE THREAD

**Issue by coryalder** [AlanQuatermain/AQGridView#14]
there is no setter method for usesPagedHorizontalScrolling. The header implies that you can change this property to get a horizontally paged view, is this just incomplete right now?

**Comment by AlanQuatermain** [comment]
Yes, this is just incomplete. It was originally defined to support something we wanted to do in Kobo, but this feature was then changed to include a smooth horizontal flow rather than paging.

Note, however, that AQGridView is a subclass of UIScrollView, so you can set it to use paging through that class's APIs.

**Comment by lapsule** [comment]
I set attributes like this:

```
self.gridView.pagingEnabled = NO;
self.gridView.layoutDirection = AQGridViewLayoutDirectionHorizontal;
```

But rows disappear except the last one.

**Comment by lapsule** [comment]
AGGridView doesn't support PagedHorizontalScrolling now, you need to rewrite some code of AQGridView and AQGridViewData yourself, I'll give a try, will back if I did it.

**Comment by klemobari** [comment]
Setting pagingEnabled to YES and layoutDirection to Horizontal still produces undefined display (items disappear at random). What approach would you recommend to make AQGridView behave like the Springboard? (horizontal paging etc.)
