### ISSUE TITLE
AQGrid reloaddata

### ISSUE THREAD

**Issue by mishuvolan** [AlanQuatermain/AQGridView#173]
hi 

i have a question about the reload data ... 
i have a webservice that provides me with data for the content and when i try to reload data from grid i get the fallowing error

 **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary setObject:forKey:]: attempt to insert nil key' ****

this the cod i use for this

NSString *jsondata = [self loadnewdata]];
NSMutableDictionary *data_resp = [jsondata JSONValue];

NSMutableArray *product = [NSMutableArray array];;
    NSDictionary *result;

```
for (result in [data_resp objectForKey:@"data"])
{
    ModelData *modData = [[ModelData new] autorelease];
    modData.identifier = [result valueForKeyPath:@"identifier"];
    modData.modpic1 = [result valueForKeyPath:@"modpic1"];
    modData.modpic2 = [result valueForKeyPath:@"modpic2"];
    [product addObject:modData];
}
```

   self.catalogProducts = product;

[gridView reloadData];

after i call reloadData the application crashes  any ideas 

thank you

**Comment by evadne** [comment]
This is a bug in your general code.  I think.  Where is the stack trace?
 Where is the full log?
- *

On Oct 18, 2012, at 6:39, mishuvolan notifications@github.com wrote:

hi

i have a question about the reload data ...
i have a webservice that provides me with data for the content and when i
try to reload data from grid i get the fallowing error

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException',
reason: '-[__NSCFDictionary setObject:forKey:]: attempt to insert nil key'

---

this the cod i use for this

NSString *jsondata = [self loadnewdata]];
NSMutableDictionary *data_resp = [jsondata JSONValue];

NSMutableArray *product = [NSMutableArray array];;
NSDictionary *result;

for (result in [data_resp objectForKey:@"data"])
{
    ModelData *modData = [[ModelData new] autorelease];
    modData.identifier = [res_cover valueForKeyPath:@"identifier"];
    modData.modpic1 = [res_cover valueForKeyPath:@"modpic1"];
    modData.modpic2 = [res_cover valueForKeyPath:@"modpic2"];
    [product addObject:modData];
}

self.catalogProducts = product;

[gridView reloadData];

after i call reloadData the application crashes any ideas

thank you

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/173.

**Comment by mishuvolan** [comment]
i have fixed my problem i was using a custom cell (.xib) and i recreated the custom cell without the xib only code and it works fine...

**Comment by evadne** [comment]
Please post your project somewhere, might be a bug in your nib or a bug
with our documentation that leads to an unexpected nib.
- *

On Oct 19, 2012, at 0:49, mishuvolan notifications@github.com wrote:

i have fixed my problem i was using a custom cell (.xib) and i recreated
the custom cell without the xib only code and it works fine...

—
Reply to this email directly or view it on
GitHubhttps://github.com/AlanQuatermain/AQGridView/issues/173#issuecomment-9592363.

**Comment by mishuvolan** [comment]
i have fixed my problem with the reload grid.

now i have a problem with the scroll. When i scroll it freezes for a short time, it's not a fluid scroll, all my data comes from a web service.

this is the code i use for populating the cell with  images

Cover *cv = [coverArray objectAtIndex:index];
NSURL *url = [NSURL URLWithString:cv.picture];
NSData *data = [NSData dataWithContentsOfURL:url];
cell.imageView.image =[UIImage imageWithData:data];

any ideeas 

thanks

**Comment by AlanQuatermain** [comment]
Your call to [NSData dataWithContentsOfURL:] is what's causing the stutter: that's performing a synchronous network operation on the main thread, which can take a while.

Your best bet is to make your cell subclass take the URL and perform the NSData call on a background thread using dispatch_async(). Then when the data is loaded you can use dispatch_async() again to go back to the main queue, where you will do two things: firstly, check that the URL property of the cell is still the same as the one you loaded (because cells get reused), then set the imageView's image property using the image you just loaded.

While the images are loading, I'd recommend that you use a local image (i.e. built into the app) as a placeholder. You'll use the same image for every cell, loaded using -imageNamed:, so they will all load very quickly.
