### ISSUE TITLE
NSIndexSet+AQIndexesOutsideSet methods not available

### ISSUE THREAD

**Issue by ghost** [AlanQuatermain/AQGridView#82]
Hi

When I use de libAQGridView.a library, and set my Search Header Paths correctly, all works, but my app crashes all the time at the NSIndexSet+AQIndexesOutsideSet category methods. It says: unrecognized selector sent to instance of NSIndexSet. It actually works, if I just copy the source h and m files into my project, but i like it clean ;)

Is there a gentle soul that can help me out?

**Comment by AlanQuatermain** [comment]
Ahhh. I found out about this the other day. By default, static libraries don't support categories. There are some linker flags you can set to enable that though. I'll see if I can dig up the details and will post them here, and update the project to include them.

**Comment by AlanQuatermain** [comment]
Found the details [on Stack Overflow](http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library). Long story short, set the `-ObjC` linker flag on the static library in your project to make the linker read in all the ObjC details, not just the classes. If that doesn't work, you can try the `-all_load` flag.

Turns out this isn't something I can set on this project though— the flag applies when a generated static lib is built into a dynamic object (i.e. the application).

**Comment by ghost** [comment]
Hi Sorry for this late answer, but I just wanted to thank you for your awesome library and support ;)
