### ISSUE TITLE
HeaderView not scrollable

### ISSUE THREAD

**Issue by Grosskopferter** [AlanQuatermain/AQGridView#99]
Hey,
is it possible to set a property so the headerView doesn't scroll with the GridView?

**Comment by evadne** [comment]
Since the grid view is a scroll view, you can reset the center of the
header view in scrollViewDidScroll, using its contentOffset, or
override its layoutSubviews and do the same thing, or just put the
view over the grid view instead of using the headerView property.

On Dec 5, 2011, at 7:26 PM, Grosskopferter
reply@reply.github.com
wrote:

**Comment by AlanQuatermain** [comment]
Unfortunately not. In your case I would simply place the header in the grid view's superview, directly above it. If you're looking for a semi-transparent header, you can put that in the superview on top of the grid view, and give the grid view an empty header of the same size, so the content lines up when the grid is scrolled to the top.

**Comment by Grosskopferter** [comment]
Thanks, that worked out well!
